### ISSUE TITLE
I want AutoImbue,have some question,can you help me 

### ISSUE THREAD

**Issue by ImBoluo** [noah-/d2bs#27]
var     npc = getUnit(1, "charsi");
	
	npc.interact();
	npc.openMenu();
	npc.useMenu(0x0fb1);

 now next step
I want move the item to Imbue,have some fanction to do it?

**Comment by noah-** [comment]
you can use submitItem();

**Comment by ImBoluo** [comment]
Thanks very much noah-
I find it.

Now ,I have a new question,
If I want to use the kolbot for Diablo 1.11b for a variety of reasons. 
what should I do?

**Comment by ImBoluo** [comment]
> you can use submitItem();

Thanks very much noah-
I find it.

Now ,I have a new question,
If I want to use the kolbot for Diablo 1.11b for a variety of reasons.
what should I do?

**Comment by ImBoluo** [comment]
don't use spoof version,  use the 1.11b version directly

**Comment by noah-** [comment]
you will need to backport d2bs for 1.11b
