### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by jaenster** [noah-/d2bs#30]
https://github.com/noah-/d2bs/blob/ddae98cc8fca0f573a271a1061b8c57aac9dcf69/JSScript.cpp#L54

Should this be:
 ScriptEngine::LockScriptList("script.getNext");

Right now its scrip.getNext

**Comment by noah-** [comment]
it’s checking to see if there are any others accessing it with the same string key, as log as they are consistent it doesn’t matter what the key is

**Comment by noah-** [comment]
it is a typo but not a bug, feel free to open pull request if it matters
