### ISSUE TITLE
hello Sir, good evening.

### ISSUE THREAD

**Issue by MWEDVAG** [noah-/d2bs#32]
hey, wanted to say as ertses, I love the D2Bot Manager. have tested many bots since 1.08, which is by far the best. I can understand integrating Mining or AD to get running costs and motivation. just remember: most of the botters I know are over 25 years old or older. ey, we all have jobs. if you need support, just integrate a popup in the next version: "we need support, either help us or in the next version is integrated AD" you will see that many will pay for it. I want it. I would suggest a price of $ 99 a year. (paypal)

just please give me an AD FREE version. You're welcome. 

Look, that's not worthy of a software. I will support you, this way is not necessary for me

![AD-example](https://user-images.githubusercontent.com/49172028/55364940-de464500-54e2-11e9-9631-d8ecd9d3d762.png)

but please do not get me wrong: many thanks for your previous work, as I have great respect for.

**Comment by noah-** [comment]
This is not part of d2bs, please post to the correct repo.
